# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `rails
# db:schema:load`. When creating a new database, `rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2020_11_01_173246) do

  create_table "comments", force: :cascade do |t|
    t.integer "user_id"
    t.integer "post_id"
    t.text "body"
    t.string "index"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "elements", force: :cascade do |t|
    t.string "element_type"
    t.string "set_name"
    t.integer "set_number"
    t.string "figure_name"
    t.string "real_name"
    t.string "rarity"
    t.boolean "unique"
    t.string "spd_symbol"
    t.string "att_symbol"
    t.string "def_symbol"
    t.string "dam_symbol"
    t.string "team_ability"
    t.integer "range"
    t.integer "targets"
    t.integer "starting_click_number"
    t.integer "starting_click_rank"
    t.text "keywords"
    t.text "improved_targeting"
    t.text "improved_movement"
    t.text "traited_powers"
    t.text "trait_text"
    t.text "movement_special_powers"
    t.integer "point_cost"
    t.text "attack_special_powers"
    t.text "defense_special_powers"
    t.text "damage_special_powers"
    t.text "movement_special_text"
    t.text "attack_special_text"
    t.text "defense_special_text"
    t.text "damage_special_text"
    t.text "click_1_powers"
    t.text "click_2_powers"
    t.text "click_3_powers"
    t.text "click_4_powers"
    t.text "click_5_powers"
    t.text "click_6_powers"
    t.text "click_7_powers"
    t.text "click_8_powers"
    t.text "click_9_powers"
    t.text "click_10_powers"
    t.text "click_11_powers"
    t.text "click_12_powers"
    t.text "click_13_powers"
    t.text "click_14_powers"
    t.text "click_15_powers"
    t.text "click_16_powers"
    t.text "click_17_powers"
    t.text "click_18_powers"
    t.text "click_19_powers"
    t.text "click_20_powers"
    t.text "click_21_powers"
    t.text "click_22_powers"
    t.text "click_23_powers"
    t.text "click_24_powers"
    t.text "click_25_powers"
    t.integer "click_1_movement"
    t.integer "click_2_movement"
    t.integer "click_3_movement"
    t.integer "click_4_movement"
    t.integer "click_5_movement"
    t.integer "click_6_movement"
    t.integer "click_7_movement"
    t.integer "click_8_movement"
    t.integer "click_9_movement"
    t.integer "click_10_movement"
    t.integer "click_11_movement"
    t.integer "click_12_movement"
    t.integer "click_13_movement"
    t.integer "click_14_movement"
    t.integer "click_15_movement"
    t.integer "click_16_movement"
    t.integer "click_17_movement"
    t.integer "click_18_movement"
    t.integer "click_19_movement"
    t.integer "click_20_movement"
    t.integer "click_21_movement"
    t.integer "click_22_movement"
    t.integer "click_23_movement"
    t.integer "click_24_movement"
    t.integer "click_25_movement"
    t.integer "click_1_attack"
    t.integer "click_2_attack"
    t.integer "click_3_attack"
    t.integer "click_4_attack"
    t.integer "click_5_attack"
    t.integer "click_6_attack"
    t.integer "click_7_attack"
    t.integer "click_8_attack"
    t.integer "click_9_attack"
    t.integer "click_10_attack"
    t.integer "click_11_attack"
    t.integer "click_12_attack"
    t.integer "click_13_attack"
    t.integer "click_14_attack"
    t.integer "click_15_attack"
    t.integer "click_16_attack"
    t.integer "click_17_attack"
    t.integer "click_18_attack"
    t.integer "click_19_attack"
    t.integer "click_20_attack"
    t.integer "click_21_attack"
    t.integer "click_22_attack"
    t.integer "click_23_attack"
    t.integer "click_24_attack"
    t.integer "click_25_attack"
    t.integer "click_1_defense"
    t.integer "click_2_defense"
    t.integer "click_3_defense"
    t.integer "click_4_defense"
    t.integer "click_5_defense"
    t.integer "click_6_defense"
    t.integer "click_7_defense"
    t.integer "click_8_defense"
    t.integer "click_9_defense"
    t.integer "click_10_defense"
    t.integer "click_11_defense"
    t.integer "click_12_defense"
    t.integer "click_13_defense"
    t.integer "click_14_defense"
    t.integer "click_15_defense"
    t.integer "click_16_defense"
    t.integer "click_17_defense"
    t.integer "click_18_defense"
    t.integer "click_19_defense"
    t.integer "click_20_defense"
    t.integer "click_21_defense"
    t.integer "click_22_defense"
    t.integer "click_23_defense"
    t.integer "click_24_defense"
    t.integer "click_25_defense"
    t.integer "click_1_damage"
    t.integer "click_2_damage"
    t.integer "click_3_damage"
    t.integer "click_4_damage"
    t.integer "click_5_damage"
    t.integer "click_6_damage"
    t.integer "click_7_damage"
    t.integer "click_8_damage"
    t.integer "click_9_damage"
    t.integer "click_10_damage"
    t.integer "click_11_damage"
    t.integer "click_12_damage"
    t.integer "click_13_damage"
    t.integer "click_14_damage"
    t.integer "click_15_damage"
    t.integer "click_16_damage"
    t.integer "click_17_damage"
    t.integer "click_18_damage"
    t.integer "click_19_damage"
    t.integer "click_20_damage"
    t.integer "click_21_damage"
    t.integer "click_22_damage"
    t.integer "click_23_damage"
    t.integer "click_24_damage"
    t.integer "click_25_damage"
    t.text "all_text"
    t.text "figure_tag"
    t.boolean "click_1_2_powers"
    t.boolean "has_ee_on_1_or_2"
    t.boolean "has_inc_on_1_or_2"
    t.boolean "has_psy_on_1_or_2"
    t.boolean "has_poi_on_1_or_2"
    t.boolean "has_ps_on_1_or_2"
    t.boolean "has_pw_on_1_or_2"
    t.boolean "has_qua_on_1_or_2"
    t.boolean "has_rev_on_1_or_2"
    t.boolean "has_se_on_1_or_2"
    t.boolean "has_sla_on_1_or_2"
    t.boolean "has_smo_on_1_or_2"
    t.boolean "has_sstr_on_1_or_2"
    t.boolean "has_stu_on_1_or_2"
    t.boolean "has_sub_on_1_or_2"
    t.boolean "has_tk_on_1_or_2"
    t.boolean "has_bf_on_1_or_2"
    t.boolean "has_cce_on_1_or_2"
    t.boolean "has_emp_on_1_or_2"
    t.boolean "has_enh_on_1_or_2"
    t.boolean "has_ew_on_1_or_2"
    t.boolean "has_ldr_on_1_or_2"
    t.boolean "has_ow_on_1_or_2"
    t.boolean "has_pc_on_1_or_2"
    t.boolean "has_ppx_on_1_or_2"
    t.boolean "has_rce_on_1_or_2"
    t.boolean "has_sc_on_1_or_2"
    t.boolean "has_sup_on_1_or_2"
    t.boolean "has_bar_on_1_or_2"
    t.boolean "has_cr_on_1_or_2"
    t.boolean "has_def_on_1_or_2"
    t.boolean "has_esd_on_1_or_2"
    t.boolean "has_imp_on_1_or_2"
    t.boolean "has_invin_on_1_or_2"
    t.boolean "has_invul_on_1_or_2"
    t.boolean "has_mmd_on_1_or_2"
    t.boolean "has_reg_on_1_or_2"
    t.boolean "has_ssen_on_1_or_2"
    t.boolean "has_tgh_on_1_or_2"
    t.boolean "has_wpw_on_1_or_2"
    t.boolean "has_chg_on_1_or_2"
    t.boolean "has_eb_on_1_or_2"
    t.boolean "has_fb_on_1_or_2"
    t.boolean "has_flu_on_1_or_2"
    t.boolean "has_fly_on_1_or_2"
    t.boolean "has_hss_on_1_or_2"
    t.boolean "has_lc_on_1_or_2"
    t.boolean "has_ls_on_1_or_2"
    t.boolean "has_mc_on_1_or_2"
    t.boolean "has_nim_on_1_or_2"
    t.boolean "has_pha_on_1_or_2"
    t.boolean "has_pla_on_1_or_2"
    t.boolean "has_rs_on_1_or_2"
    t.boolean "has_sli_on_1_or_2"
    t.boolean "has_ss_on_1_or_2"
    t.boolean "has_sth_on_1_or_2"
    t.boolean "has_bcf_on_dial"
    t.boolean "has_ee_on_dial"
    t.boolean "has_inc_on_dial"
    t.boolean "has_psy_on_dial"
    t.boolean "has_poi_on_dial"
    t.boolean "has_ps_on_dial"
    t.boolean "has_pw_on_dial"
    t.boolean "has_qua_on_dial"
    t.boolean "has_rev_on_dial"
    t.boolean "has_se_on_dial"
    t.boolean "has_sla_on_dial"
    t.boolean "has_smo_on_dial"
    t.boolean "has_sstr_on_dial"
    t.boolean "has_stu_on_dial"
    t.boolean "has_sub_on_dial"
    t.boolean "has_tk_on_dial"
    t.boolean "has_bf_on_dial"
    t.boolean "has_cce_on_dial"
    t.boolean "has_emp_on_dial"
    t.boolean "has_enh_on_dial"
    t.boolean "has_ew_on_dial"
    t.boolean "has_ldr_on_dial"
    t.boolean "has_ow_on_dial"
    t.boolean "has_pc_on_dial"
    t.boolean "has_ppx_on_dial"
    t.boolean "has_rce_on_dial"
    t.boolean "has_sc_on_dial"
    t.boolean "has_sup_on_dial"
    t.boolean "has_bar_on_dial"
    t.boolean "has_cr_on_dial"
    t.boolean "has_def_on_dial"
    t.boolean "has_esd_on_dial"
    t.boolean "has_imp_on_dial"
    t.boolean "has_invin_on_dial"
    t.boolean "has_invul_on_dial"
    t.boolean "has_mmd_on_dial"
    t.boolean "has_reg_on_dial"
    t.boolean "has_ssen_on_dial"
    t.boolean "has_tgh_on_dial"
    t.boolean "has_wpw_on_dial"
    t.boolean "has_chg_on_dial"
    t.boolean "has_eb_on_dial"
    t.boolean "has_fb_on_dial"
    t.boolean "has_flu_on_dial"
    t.boolean "has_fly_on_dial"
    t.boolean "has_hss_on_dial"
    t.boolean "has_lc_on_dial"
    t.boolean "has_ls_on_dial"
    t.boolean "has_mc_on_dial"
    t.boolean "has_nim_on_dial"
    t.boolean "has_pha_on_dial"
    t.boolean "has_pla_on_dial"
    t.boolean "has_rs_on_dial"
    t.boolean "has_sli_on_dial"
    t.boolean "has_ss_on_dial"
    t.boolean "has_sth_on_dial"
    t.integer "max_att_1_2"
    t.integer "max_att_dial"
    t.integer "max_spd_1_2"
    t.integer "max_spd_dial"
    t.integer "max_def_1_2"
    t.integer "max_def_dial"
    t.integer "max_dam_1_2"
    t.integer "max_dam_dial"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

# Could not dump table "forces" because of following StandardError
#   Unknown type 'array' for column 'main_force_figures'

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  add_foreign_key "forces", "users"
end
